# Site
repository: nilssta/nilssta.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nils Hendrik Stanislawski
title: Research Associate & Ph. D. Candidate

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: nilssta
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: nils-stanislawski-959553213
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-9283-8155

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nils and I'm a research associate and Ph.D. student at the Leibniz University Hannover in Germany.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: OpenAXES
        link: github.com/OpenAXES-IMU/OpenAXES
        # link_text: Project Website
        additional_links:
          - title: OpenAXES-IMU/OpenAXES
            icon: fab fa-github
            url: github.com/OpenAXES-IMU/OpenAXES
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Hardware design files and source code for an open-access wireless IMU developed at the Institute of Microelectronic Systems at the Leibniz University Hannover, Germany.
      - layout: top-middle
        title: mca-his
        link: github.com/IMS-AS-LUH/mca-his
        # link_text: Project Website
        additional_links:
          - title: IMS-AS-LUH/mca-his
            icon: fab fa-github
            url: github.com/IMS-AS-LUH/mca-his
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Custom Health Information System (HIS) used in the context of a university based diagnostic laboratory and mobile teststations for SARS-CoV-2. This project was one of the most intense I've ever worked on but also very fulfilling. A lot of our findings and detailed descriptions of our procedures and technical setup are published [freely accessible](https://data.uni-hannover.de/de/dataset/mca-dataset).

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Institute of Microelectronic Systems
        link: ims.uni-hannover.de/en/
        sub_title: Research Associate & Ph. D. Candidate
        caption: August 2016 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #   Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      - layout: left
        title: Institute of Technical Chemistry
        link: tci.uni-hannover.de/
        sub_title: Research Associate
        caption: August 2016 - December 2018
      - layout: left
        title: Institute of Microelectronic Systems
        link: ims.uni-hannover.de/en/
        sub_title: Student Assistant
        caption: April 2014 - July 2016
      - layout: left
        title: Hamilton Medical
        link: hamilton-medical.com/
        sub_title: Internship
        caption: October 2013 - March 2014
      - layout: left
        title: IngMar Medical Ltd.
        link: ingmarmed.com/
        sub_title: Internship
        caption: February 2013 - September 2013
      - layout: left
        title: Barge Ingenieure
        link: bargeplan.de/
        sub_title: Student Trainee
        caption: February 2013 - September 2013

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Leibniz University Hannover
        caption: 2014 - 2016
        sub_title: MSc Electrical Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      - layout: left
        title: Jade University of Applied Sciences
        caption: 2010 - 2014
        sub_title: BEng Biomedical Engineering

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in biomedical, mechanical, and software engineering some of my other interests and hobbies are:
      - Photography
      - Board games
      - Woodworking

# Footer
footer_show_references: true
references_title: References on request

# Build settings
remote_theme: nilssta/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
